ALTER TABLE Products_td ADD FOREIGN KEY (Category_id) REFERENCES Categories_td (id);
INSERT INTO Products_td (Category_id, Product_name) VALUES (1 ,"Milk 1l");
INSERT INTO Products_td (Category_id, Product_name) VALUES (1 ,"Imasi");
INSERT INTO Products_td (Category_id, Product_name) VALUES (1 ,"Bread");
INSERT INTO Products_td (Category_id, Product_name) VALUES (2 ,"Chakalaka Can");
INSERT INTO Products_td (Category_id, Product_name) VALUES (2 ,"Gold Dish Vegetable Curry Can");
INSERT INTO Products_td (Category_id, Product_name) VALUES (3 ,"Fanta 500ml");
INSERT INTO Products_td (Category_id, Product_name) VALUES (3 ,"Coke 500ml");
INSERT INTO Products_td (Category_id, Product_name) VALUES (3 ,"Cream Soda 500ml");
INSERT INTO Products_td (Category_id, Product_name) VALUES (4 ,"Iwisa Pap 5kg");
INSERT INTO Products_td (Category_id, Product_name) VALUES (4 ,"Top Class Soy Mince");
INSERT INTO Products_td (Category_id, Product_name) VALUES (5 ,"Shampoo 1 litre");
INSERT INTO Products_td (Category_id, Product_name) VALUES (5 ,"Soap Bar");
INSERT INTO Products_td (Category_id, Product_name) VALUES (6 ,"Bananas - loose");
INSERT INTO Products_td (Category_id, Product_name) VALUES (6 ,"Apples - loose");
INSERT INTO Products_td (Category_id, Product_name) VALUES (7 ,"Mixed Sweets 5s");
INSERT INTO Products_td (Category_id, Product_name) VALUES (7 ,"Heart Chocolates");
INSERT INTO Products_td (Category_id, Product_name) VALUES (8 ,"Rose (plastic)");
INSERT INTO Products_td (Category_id, Product_name) VALUES (8 ,"Valentine Cards");
